name: pyLint

on:
  push:
    paths:
      - "**.py"

jobs:
  PEP8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.x
      - name: Install Python lint libraries
        run: |
          pip install autopep8 autoflake isort black
      - name: Check for showstoppers
        run: autopep8 --verbose --in-place --recursive --aggressive --aggressive . *.py
      - name: Remove unused imports and variables
        run: autoflake --in-place --recursive --remove-all-unused-imports --remove-unused-variables .
      - name: lint with isort and black
        run: |
          isort .
          black --fast .
      # commit changes
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'pyLint: auto-fixes'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: TeamUltroid
          commit_user_email: teamultroid@ultroid.tech
          commit_author: TeamUltroid <teamultroid@ultroid.tech>
