name: Replacer
on:
  push:
  workflow_dispatch:
jobs:
  Replace:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: " exit("
          replace: " import sys; sys.exit("
          regex: false
          exclude: .github/**
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Replacer'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: 1Danish-00
          commit_user_email: danish@ultroid.tech
          commit_author: 1Danish-00 <danish@ultroid.tech>
